export enum CONSTS {
    // BYTES_PERCENTAGE_ID = 'bytes-percentage',
    // BYTES_TOTAL_ID = 'bytes-total',
    BYTES_USE_ID = "bytes-use",
    CACHE_MESSAGE_COUNT_ID = "cache-message-count",
    CACHE_MESSAGE_ID = "cache-message",
    CHAT_BUTTON_DIV_ID = "rs-display-chat-button-div",
    CHAT_BUTTON_ID = "rs-display-chat-button",
    DATA_AMOUNT = "data-amount",
    DELETE_STREAM_ID = "delete-stream",
    DOWNLOAD_CSV_ID = "download-csv",
    ERROR_ID = "load-error",
    HIDDEN_CLASS = "hidden",
    LEVEL_STYLE_ID = "rant-styles",
    OPEN_OPTIONS_ID = "open-options",
    POPOUT_ICON_ID = "popout-icon",
    POPUP_CLASS = "popup",
    RANT_LIST_ID = "rant-list",
    READ_CHECK = "read-check",
    REFRESH_ICON = "refresh-icon",
    RESIZE_ID = "resize",
    SIDEBAR_ID = "rs-chats",
    SIDEBAR_TITLE_ID = "sidebar-title",
    STREAM_CREATOR = "stream-creator",
    STREAM_DATA = "stream-data",
    STREAM_DATE = "stream-date",
    STREAM_TITLE = "stream-title",
    TOTAL_ID = "rant-total",
}

export const CHAT_POPUP_REGEX = /\/chat\/popup\/(\d+)/
